### ISSUE TITLE
modify the resolution and z value of cameras in the code but not in camera.txt 

### ISSUE THREAD

**Issue by xiayuyang** [fubel/synthehicle#10]
I have a problem, if I modify the z value and resolution of the camera in the code (run.py) but do not modify the camera's z value and resolution in the camera.txt. Will this affect subsequent gt.txt generated based on lidar and camera? In addition, in this case, does the lidar need to adjust its parameters (corresponding to resolution)?

**Comment by fubel** [comment]
If I remember correctly, the cameras are initialized using the camera.txt. If you then modify the z-value, the generated data will be fine, however, you should store the "new" camera matrix because the intrinsics and extrinsics in "camera.txt" will be wrong.

**Comment by xiayuyang** [comment]
But I find that the intrinsics and extrinsics in camera.txt  is not used in the code. Can I understand that they are just a log information?

**Comment by xiayuyang** [comment]
In addition, I'm interested in how you determined the location and rotation of each camera. This seems to be a tedious operation that requires many trials and errors.

**Comment by fubel** [comment]
> But I find that the intrinsics and extrinsics in camera.txt is not used in the code. Can I understand that they are just a log information?

They are loaded here:
https://github.com/fubel/synthehicle/blob/de6759714c15e8314dc1702586a5fca530835d67/carla/generate_carla_data/multi_camera/run.py#L364

The cameras are spawned using the info in the camera_*.txt files. 

> In addition, I'm interested in how you determined the location and rotation of each camera. This seems to be a tedious operation that requires many trials and errors.

It’s not very tedious I think. You can fly around with the camera in Carla and write a little script that saves the camera position / rotation. Methods for this can be found in the `set_camera_position.py` script (actually I think this script should work out if the box: fly to a the desired position in Carla and then run the script)
