### ISSUE TITLE
Segmentation Files

### ISSUE THREAD

**Issue by vineetrshenoy** [fubel/synthehicle#6]
Hi, I have downloaded the data included the [segmentation files](https://github.com/fubel/synthehicle/wiki/Download). However, it seems like it is only the image results (i.e. png). Are there ground-truth `.json`. or `.txt` files that correspond to the segmentations?

**Comment by vineetrshenoy** [comment]
Ok, thanks for letting me know!

**Comment by vineetrshenoy** [comment]
Just to follow-up, do you have code for your suggestions (i.e. png to polygon and finding the exterior coordinates)?

**Comment by fubel** [comment]
I think that might be a good way to do it:
https://www.immersivelimit.com/create-coco-annotations-from-scratch

It uses the shapely library to find polygons based on color, and then converts the exterior to arrays for COCO.
