### ISSUE TITLE
Can we have gt file of  test datatset？

### ISSUE THREAD

**Issue by niiish32x** [fubel/synthehicle#7]
I have download the dataset. I  can only find that train data have gt file, but test data doesn't . So that i can't evaluate my method on test  data.

**Comment by myeongjun-ds** [comment]
@niiish32x Hello !
I also faced no test data GT problem. How can you get the GT ?
Thank you.

**Comment by fubel** [comment]
@myeongjun-ds The MTMC tracking ground truth for the test set can be found here:
https://drive.google.com/file/d/1OTuPwZFq9BN7mbfovJ0XRwFJyXU_WxwA/view?usp=share_link 

We have not released other ground truth data (depth maps, segmentations, etc.) for the test set yet.

**Comment by myeongjun-ds** [comment]
@fubel Thank you for sharing gt data !
Can I get a out_bbox file ?

**Comment by fubel** [comment]
Absolutely! Forgot to mention, we've uploaded the raw out_bbox files for train and test to hugging face:
https://huggingface.co/datasets/fubel/synthehicle/tree/main/test 

These were used in some papers to compute BEV-based tracking results for Synthehicle, but we have no official evaluation code for this here in the repo. Let me know if you have any questions on how to use this data for evaluation.

**Comment by myeongjun-ds** [comment]
Thank you for quick response !
I can available both of data.

**Comment by myeongjun-ds** [comment]
@fubel Hi !
Thank you for sharing huggingface dataset link.
The data I received from huggingface doesn't seem to be working properly. Could you please upload only the out_bbox to google drive?
