### ISSUE TITLE
ground truth 

### ISSUE THREAD

**Issue by xiayuyang** [fubel/synthehicle#9]
How is the gt.txt file generated? Looking forward to your help.

**Comment by fubel** [comment]
Hey,

the `gt.txt`-files are generated from the information in the `out_bbox` directories (which come directly from CARLA) by converting the information into MOT-format.  

Does this answer your question?

**Comment by xiayuyang** [comment]
> Hey,
> 
> the `gt.txt`-files are generated from the information in the `out_bbox` directories (which come directly from CARLA) by converting the information into MOT-format.
> 
> Does this answer your question?

Certainly. I'm reading your code carefully and it's very clear.

**Comment by xiayuyang** [comment]
I have another question. if I only need to tracking data, do I only need to use the data from RGB camera and ray_cast_semantic lidar?

**Comment by fubel** [comment]
The RGB cameras will record the frames (images) and the bounding boxes are obtained from the CARLA engine. The boxes are, however, also rendered even if the object in question is occluded (e.g., by a building). Therefore we use the semantic lidar to determine which of the boxes are actually visible.

In short: If you want to generate data for tracking (2D or 3D) only, you only need the RGB cameras and the semantic lidar.
